%%%%%%% R-Clustering demo file
% This demo applies the R-Clustering segmentation algorithm on a set
% captured by a lifelogging wearable camera.
%
% For a visualization of the result, use the 'plot_params' variable in 
% loadParametersDemo.m.

% Load parameters
loadParametersDemo;

% Folder with lifelogging images that we want to segment
%folder = [pwd '/test_data/Subject1'];'/media/HDD_2TB/DATASETS/LIFELOG_DATASETS/Narrative/imageSets/Berta/27_Crop_informative_images'
%folders = { '/media/My_Book/Datos_Lifelogging/Narrative2/Berta/2016/05/13/13_Crop', '/media/My_Book/Datos_Lifelogging/Narrative2/Berta/2016/05/14/14_Crop','/media/My_Book/Datos_Lifelogging/Narrative2/Berta/2016/05/15/15_Crop', '/media/My_Book/Datos_Lifelogging/Narrative2/Berta/2016/05/16/16_Crop', '/media/My_Book/Datos_Lifelogging/Narrative2/Berta/2016/05/17/17_Crop', '/media/My_Book/Datos_Lifelogging/Narrative2/Berta/2016/05/18/18_Crop', '/media/My_Book/Datos_Lifelogging/Narrative2/Berta/2016/05/19/19_Crop'};

folders = {
%     '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-gabriel/20_Crop',...
%     '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-gabriel/21_Crop',...
%     '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/05/05_30_Crop',...
%     '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_01_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_08_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_10_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_12_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_13_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_15_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_18_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/06/06_21_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_07_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_12_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_13_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_14_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_15_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_18_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_20_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_22_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_23_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_24_Crop',...
    '/media/My_Book/Datos_Lifelogging/Narrative2/Send2Christian/2016-maya/07/07_27_Crop'};
% folders = {'/media/My_Book/Datos_Lifelogging/Narrative/Pacientes/Paciente2/11/26_Crop_lunch'}

for i=1:length(folders)
    folder = folders{i};
    % Format of the images in 'folder
    images_format = '.jpg';


% .csv, .txt or .xls file with the GT segmentation of the data
% (OPTIONAL, set to empty string if you don't want an evaluation of the result) 
% GT_path = [pwd '/test_data/GT/GT_Subject1.csv'];
    GT_path ='';

    %% The R-Clustering segmentation is applied
    segmentation = RClustering(folder, images_format, data_params, R_Clustering_params, CNN_params, Semantic_params, plot_params, GT_path);
    caffe('reset');
    clear caffe;
end
    disp('Done');
    exit
